name: "Build & deploy for Linux"

on:
  push:
    tags: ['v*']

jobs:
  build_linux:
    name: Build and release Linux app
    strategy:
      matrix:
        os:
          # - ubuntu-latest
         - ubuntu-24.04-arm
        include:
#        - label: x86_64
#          os: ubuntu-latest
        - label: aarch64
          os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install missing packages
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev desktop-file-utils

    - name: Setup Flutter
      run: |
        git clone --depth 1 --branch stable https://github.com/flutter/flutter.git $RUNNER_TEMP/flutter
        echo "$RUNNER_TEMP/flutter/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Flutter version
      run: flutter --version

    - name: Install melos
      run: flutter pub global activate melos
    
    - name: Check melos version
      run: melos --version

    - name: Build for linux
      run: flutter build linux --release

    - name: Tar linux package
      run: |
        arch=$(ls build/linux)
        tar -C build/linux/$arch/release/bundle -czf converternow-linux-${{ matrix.label }}.tar.gz .

    - name: Build appimage
      run: |
        arch=$(ls build/linux)
        wget https://github.com/AppImage/appimagetool/releases/latest/download/appimagetool-${{ matrix.label }}.AppImage
        chmod +x appimagetool-${{ matrix.label }}.AppImage
        mkdir ConverterNOW.AppDir
        cp -r build/linux/$arch/release/bundle/* ConverterNOW.AppDir
        cp assets/app_icons/logo.svg ConverterNOW.AppDir
        echo -e '#!/bin/sh\ncd "$(dirname "$0")"\nexec ./converternow' > ConverterNOW.AppDir/AppRun
        chmod +x ConverterNOW.AppDir/AppRun
        cp snap/gui/converternow.desktop ConverterNOW.AppDir
        desktop-file-edit --set-icon="logo" --set-key="Exec" --set-value="converternow %u" ConverterNOW.AppDir/converternow.desktop
        APPIMAGETOOL_APP_NAME=converternow ./appimagetool-${{ matrix.label }}.AppImage ConverterNOW.AppDir

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "converternow-linux-${{ matrix.label }}.tar.gz,converternow-${{ matrix.label }}.AppImage"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
        allowUpdates: true
